version: '3.7'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poeaa
    restart: always
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "poeaa"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 15432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      postgres_network:
        aliases:
          - postgres_host
volumes:
  pgdata: {}

networks:
  postgres_network:
    name: postgres_net
    driver: bridge